apiVersion: v1
kind: Service
metadata:
  name: a
  labels:
    app: a
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
    nodePort: 30100
  selector: 
    app: a
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: a-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: a
        version: v1
    spec:
      containers:
      - name: a
        image: orcaselite/schematic-abcde:gen-a
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: b
  labels:
    app: b
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector: 
    app: b
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: b-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: b
        version: v1
    spec:
      containers:
      - name: b
        image: orcaselite/schematic-abcde:gen-b
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: c
  labels:
    app: c
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector: 
    app: c
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: c-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: c
        version: v1
    spec:
      containers:
      - name: c
        image: orcaselite/schematic-abcde:gen-c
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: d
  labels:
    app: d
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector: 
    app: d
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: d-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: d
        version: v1
    spec:
      containers:
      - name: d
        image: orcaselite/schematic-abcde:gen-d
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: e
  labels:
    app: e
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector: 
    app: e
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: e-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: e
        version: v1
    spec:
      containers:
      - name: e
        image: orcaselite/schematic-abcde:gen-e
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
