apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: e
spec:
  host: e
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      http:
        consecutiveErrors: 2
        interval: 10s
        baseEjectionTime: 1m
        maxEjectionPercent: 100
