apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: f
spec:
  hosts:
  - f
  http:
  - fault:
      delay:
        percent: 100
        fixedDelay: 3s
    match:
    - uri:
        prefix: "/f2"
    route:
    - destination:
        host: f
  - route:
    - destination:
        host: f
