apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: d-route
spec:
  hosts:
  - d
  http:
  - route:
    - destination:
        host: d
    fault:
      abort:
        percent: 50
        httpStatus: 400
