apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: f
spec:
  hosts:
  - f
  http:
  - fault:
      abort:
        percent: 100
        httpStatus: 502
    match:
    - uri:
        prefix: "/f2"
    route:
    - destination:
        host: f
  - route:
    - destination:
        host: f
