apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: f
spec:
  hosts:
  - f
  http:
  - match:
    - uri:
        prefix: "/f2"
    route:
    - destination:
        host: f
    timeout: 1s
