apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: e
spec:
  hosts:
  - e
  http:
  - match:
    - uri:
        prefix: "/e2"
    route:
    - destination:
        host: e
    timeout: 1s
  - route:
    - destination:
        host: e
