version: '2'

services:
  jaeger: 
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  a:
    build: gen-a/.
    ports: 
      - "8080:8080"
    environment:
      - JAEGER_SERVICE_NAME=a
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_MAX_QUEUE_SIZE=10000 
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    links:
      - "b"
      - "c"

  b:
    build: gen-b/.
    environment:
      - JAEGER_SERVICE_NAME=b
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_MAX_QUEUE_SIZE=10000 
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    links:
      - "d"
      - "e"

  c:
    build: gen-c/.
    environment:
      - JAEGER_SERVICE_NAME=c
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_MAX_QUEUE_SIZE=10000 
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    links:
      - "e"
  
  d:
    build: gen-d/.
    environment:
      - JAEGER_SERVICE_NAME=d
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_MAX_QUEUE_SIZE=10000 
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
  
  e:
    build: gen-e/.
    environment:
      - JAEGER_SERVICE_NAME=e
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_MAX_QUEUE_SIZE=10000 
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
