apiVersion: v1
kind: ReplicationController
metadata:
  name: c
  labels:
    name: c
spec:
  replicas: 1
  selector:
    name: c
  template:
    metadata:
      labels:
        name: c
    spec:
      containers:
      - name: c
        image: my/c
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: c
  labels:
    name: c
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector: 
    name: c
