apiVersion: v1
kind: ReplicationController
metadata:
  name: a
  labels:
    name: a
spec:
  replicas: 1
  selector:
    name: a
  template:
    metadata:
      labels:
        name: a
    spec:
      containers:
      - name: a
        image: my/a
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: a
  labels:
    name: a
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector: 
    name: a
