apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: abcde-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: abcde
spec:
  hosts:
  - "*"
  gateways:
  - abcde-gateway
  http:
  - match:
    - uri:
        exact: /a1
    - uri:
        exact: /a2
    route:
    - destination:
        host: a
        port:
          number: 8080
  - match:
    - uri:
        exact: /b1
    - uri:
        exact: /b2
    route:
    - destination:
        host: b
        port:
          number: 8080
  - match:
    - uri:
        exact: /c1
    - uri:
        exact: /c2
    route:
    - destination:
        host: c
        port:
          number: 8080
  - match:
    - uri:
        exact: /d1
    - uri:
        exact: /d2
    route:
    - destination:
        host: d
        port:
          number: 8080
  - match:
    - uri:
        exact: /e1
    - uri:
        exact: /e2
    route:
    - destination:
        host: e
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: a
spec:
  hosts:
  - a
  http:
  - route:
    - destination:
        host: a
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: b
spec:
  hosts:
  - b
  http:
  - route:
    - destination:
        host: b
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: c
spec:
  hosts:
  - c
  http:
  - route:
    - destination:
        host: c
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: d
spec:
  hosts:
  - d
  http:
  - route:
    - destination:
        host: d
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: e
spec:
  hosts:
  - e
  http:
  - route:
    - destination:
        host: e
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: f
spec:
  hosts:
  - f
  http:
  - route:
    - destination:
        host: f
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: a
spec:
  host: a
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: b
spec:
  host: b
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: c
spec:
  host: c
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: d
spec:
  host: d
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: e
spec:
  host: e
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: f
spec:
  host: f
